# Generated by Django 2.2.5 on 2020-04-14 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_auto_20200409_0702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='participnts',
            new_name='participants',
        ),
    ]
